# Generated by Django 3.2.7 on 2023-05-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_options_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
